name: Aprendiendo Github Actions
on: [push]
jobs:
  mi-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/setup-node@v3
      - run: node main.js
